"""initial database schema

Revision ID: 8154b5851fbf
Revises: 
Create Date: 2025-11-05 19:03:11.230028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8154b5851fbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart_configs', 'config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Chart configuration (JSON object)',
               existing_nullable=False)
    op.alter_column('chart_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='Record creation timestamp',
               existing_comment='Record creation timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('chart_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='Record last update timestamp',
               existing_comment='Record last update timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('chart_configs', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Deletion timestamp',
               existing_comment='Deletion timestamp (UTC)',
               existing_nullable=True)
    op.create_index('ix_chart_deleted_updated', 'chart_configs', ['is_deleted', 'updated_at'], unique=False)
    op.alter_column('datasets', 'columns',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='[]',
               existing_comment='List of column names (JSON array)',
               existing_nullable=False)
    op.alter_column('datasets', 'metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Additional metadata (JSON object)',
               existing_nullable=False)
    op.alter_column('datasets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='Record creation timestamp',
               existing_comment='Record creation timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('datasets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='Record last update timestamp',
               existing_comment='Record last update timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('datasets', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Deletion timestamp',
               existing_comment='Deletion timestamp (UTC)',
               existing_nullable=True)
    op.create_index('ix_dataset_deleted_updated', 'datasets', ['is_deleted', 'updated_at'], unique=False)
    op.alter_column('import_tasks', 'import_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='Import file type (csv, excel, qlib, json)',
               existing_comment='Import file type',
               existing_nullable=False)
    op.alter_column('import_tasks', 'file_path',
               existing_type=mysql.TEXT(),
               comment='Server file path where uploaded file is stored',
               existing_comment='Server file path',
               existing_nullable=False)
    op.alter_column('import_tasks', 'file_size',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('import_tasks', 'total_rows',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='Total rows to process',
               existing_nullable=False)
    op.alter_column('import_tasks', 'processed_rows',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               comment='Number of rows processed',
               existing_comment='Rows processed',
               existing_nullable=False)
    op.alter_column('import_tasks', 'progress_percentage',
               existing_type=mysql.FLOAT(),
               server_default=None,
               comment='Progress percentage (0-100)',
               existing_comment='Progress percentage',
               existing_nullable=False)
    op.alter_column('import_tasks', 'error_count',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               comment='Number of errors encountered',
               existing_comment='Error count',
               existing_nullable=False)
    op.alter_column('import_tasks', 'error_message',
               existing_type=mysql.TEXT(),
               comment='Error message if task failed',
               existing_comment='Error message if failed',
               existing_nullable=True)
    op.alter_column('import_tasks', 'validation_errors',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='List of validation errors (JSON array)',
               existing_comment='Validation errors array',
               existing_nullable=True)
    op.alter_column('import_tasks', 'parsing_metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='Parsing metadata (columns detected, data types, etc.)',
               existing_comment='Parsing metadata',
               existing_nullable=True)
    op.alter_column('import_tasks', 'import_config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='Import configuration (delimiter, encoding, skip rows, etc.)',
               existing_comment='Import configuration',
               existing_nullable=True)
    op.alter_column('import_tasks', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='User who initiated the import (optional for now)',
               existing_comment='User who initiated import',
               existing_nullable=True)
    op.alter_column('import_tasks', 'dataset_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='ID of dataset created or updated by this import',
               existing_comment='Created/updated dataset ID',
               existing_nullable=True)
    op.alter_column('import_tasks', 'id',
               existing_type=mysql.VARCHAR(length=36),
               comment='Primary key (UUID)',
               existing_comment='UUID primary key',
               existing_nullable=False)
    op.alter_column('import_tasks', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               comment='Record creation timestamp',
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('import_tasks', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               comment='Record last update timestamp',
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('import_tasks', 'deleted_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Deletion timestamp',
               existing_comment='Soft delete timestamp',
               existing_nullable=True)
    op.alter_column('import_tasks', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               comment='User ID who created this record',
               existing_comment='User who created this record',
               existing_nullable=True)
    op.alter_column('import_tasks', 'updated_by',
               existing_type=mysql.VARCHAR(length=255),
               comment='User ID who last updated this record',
               existing_comment='User who last updated this record',
               existing_nullable=True)
    op.create_index('ix_import_dataset_deleted_created', 'import_tasks', ['dataset_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_import_deleted_status_created', 'import_tasks', ['is_deleted', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_import_tasks_is_deleted'), 'import_tasks', ['is_deleted'], unique=False)
    op.create_index('ix_import_user_deleted_created', 'import_tasks', ['user_id', 'is_deleted', 'created_at'], unique=False)
    op.alter_column('user_preferences', 'completed_guides',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='[]',
               existing_comment='List of completed onboarding guide IDs (JSON array)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'settings',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Additional user-specific settings (JSON object)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='Record creation timestamp',
               existing_comment='Record creation timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='Record last update timestamp',
               existing_comment='Record last update timestamp (UTC)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Deletion timestamp',
               existing_comment='Deletion timestamp (UTC)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preferences', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Deletion timestamp (UTC)',
               existing_comment='Deletion timestamp',
               existing_nullable=True)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               comment='Record last update timestamp (UTC)',
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('user_preferences', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               comment='Record creation timestamp (UTC)',
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('user_preferences', 'settings',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Additional user-specific settings (JSON object)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'completed_guides',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'[]'"),
               existing_comment='List of completed onboarding guide IDs (JSON array)',
               existing_nullable=False)
    op.drop_index('ix_import_user_deleted_created', table_name='import_tasks')
    op.drop_index(op.f('ix_import_tasks_is_deleted'), table_name='import_tasks')
    op.drop_index('ix_import_deleted_status_created', table_name='import_tasks')
    op.drop_index('ix_import_dataset_deleted_created', table_name='import_tasks')
    op.alter_column('import_tasks', 'updated_by',
               existing_type=mysql.VARCHAR(length=255),
               comment='User who last updated this record',
               existing_comment='User ID who last updated this record',
               existing_nullable=True)
    op.alter_column('import_tasks', 'created_by',
               existing_type=mysql.VARCHAR(length=255),
               comment='User who created this record',
               existing_comment='User ID who created this record',
               existing_nullable=True)
    op.alter_column('import_tasks', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               comment='Soft delete timestamp',
               existing_comment='Deletion timestamp',
               existing_nullable=True)
    op.alter_column('import_tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               comment='Last update timestamp',
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('import_tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('current_timestamp()'),
               type_=mysql.TIMESTAMP(),
               comment='Creation timestamp',
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('import_tasks', 'id',
               existing_type=mysql.VARCHAR(length=36),
               comment='UUID primary key',
               existing_comment='Primary key (UUID)',
               existing_nullable=False)
    op.alter_column('import_tasks', 'dataset_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='Created/updated dataset ID',
               existing_comment='ID of dataset created or updated by this import',
               existing_nullable=True)
    op.alter_column('import_tasks', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               comment='User who initiated import',
               existing_comment='User who initiated the import (optional for now)',
               existing_nullable=True)
    op.alter_column('import_tasks', 'import_config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='Import configuration',
               existing_comment='Import configuration (delimiter, encoding, skip rows, etc.)',
               existing_nullable=True)
    op.alter_column('import_tasks', 'parsing_metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='Parsing metadata',
               existing_comment='Parsing metadata (columns detected, data types, etc.)',
               existing_nullable=True)
    op.alter_column('import_tasks', 'validation_errors',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               comment='Validation errors array',
               existing_comment='List of validation errors (JSON array)',
               existing_nullable=True)
    op.alter_column('import_tasks', 'error_message',
               existing_type=mysql.TEXT(),
               comment='Error message if failed',
               existing_comment='Error message if task failed',
               existing_nullable=True)
    op.alter_column('import_tasks', 'error_count',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('0'),
               comment='Error count',
               existing_comment='Number of errors encountered',
               existing_nullable=False)
    op.alter_column('import_tasks', 'progress_percentage',
               existing_type=mysql.FLOAT(),
               server_default=sa.text('0'),
               comment='Progress percentage',
               existing_comment='Progress percentage (0-100)',
               existing_nullable=False)
    op.alter_column('import_tasks', 'processed_rows',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('0'),
               comment='Rows processed',
               existing_comment='Number of rows processed',
               existing_nullable=False)
    op.alter_column('import_tasks', 'total_rows',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('0'),
               existing_comment='Total rows to process',
               existing_nullable=False)
    op.alter_column('import_tasks', 'file_size',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text('0'),
               existing_comment='File size in bytes',
               existing_nullable=False)
    op.alter_column('import_tasks', 'file_path',
               existing_type=mysql.TEXT(),
               comment='Server file path',
               existing_comment='Server file path where uploaded file is stored',
               existing_nullable=False)
    op.alter_column('import_tasks', 'import_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='Import file type',
               existing_comment='Import file type (csv, excel, qlib, json)',
               existing_nullable=False)
    op.drop_index('ix_dataset_deleted_updated', table_name='datasets')
    op.alter_column('datasets', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Deletion timestamp (UTC)',
               existing_comment='Deletion timestamp',
               existing_nullable=True)
    op.alter_column('datasets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               comment='Record last update timestamp (UTC)',
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('datasets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               comment='Record creation timestamp (UTC)',
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('datasets', 'metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Additional metadata (JSON object)',
               existing_nullable=False)
    op.alter_column('datasets', 'columns',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'[]'"),
               existing_comment='List of column names (JSON array)',
               existing_nullable=False)
    op.drop_index('ix_chart_deleted_updated', table_name='chart_configs')
    op.alter_column('chart_configs', 'deleted_at',
               existing_type=mysql.DATETIME(),
               comment='Deletion timestamp (UTC)',
               existing_comment='Deletion timestamp',
               existing_nullable=True)
    op.alter_column('chart_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               comment='Record last update timestamp (UTC)',
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('chart_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               comment='Record creation timestamp (UTC)',
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('chart_configs', 'config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Chart configuration (JSON object)',
               existing_nullable=False)
    # ### end Alembic commands ###
