"""add_strategy_tables

Revision ID: 8043d0765021
Revises: 9a2b3c4d5e6f
Create Date: 2025-11-05 23:51:22.742876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8043d0765021'
down_revision: Union[str, None] = '9a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_templates',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Template name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Template description'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Strategy category (TREND_FOLLOWING, OSCILLATION, MULTI_FACTOR)'),
    sa.Column('logic_flow', sa.JSON(), nullable=False, comment='Visual flow diagram data (nodes and edges)'),
    sa.Column('parameters', sa.JSON(), server_default='{}', nullable=False, comment='Parameter definitions with defaults and ranges'),
    sa.Column('is_system_template', sa.Boolean(), server_default='0', nullable=False, comment='True for built-in templates, False for custom'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User ID for custom templates (NULL for system templates)'),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False, comment='Number of times template has been used'),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), server_default='0.0', nullable=False, comment='Average rating (0-5)'),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False, comment='Number of ratings received'),
    sa.Column('backtest_example', sa.JSON(), nullable=True, comment='Historical backtest results for demonstration'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Deletion timestamp'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='User ID who last updated this record'),
    sa.CheckConstraint('rating_average >= 0 AND rating_average <= 5', name='check_rating_average_range'),
    sa.CheckConstraint('rating_count >= 0', name='check_rating_count_non_negative'),
    sa.CheckConstraint('usage_count >= 0', name='check_usage_count_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    comment='Strategy template storage table',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_strategy_templates_category'), 'strategy_templates', ['category'], unique=False)
    op.create_index(op.f('ix_strategy_templates_is_deleted'), 'strategy_templates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_strategy_templates_is_system_template'), 'strategy_templates', ['is_system_template'], unique=False)
    op.create_index(op.f('ix_strategy_templates_name'), 'strategy_templates', ['name'], unique=False)
    op.create_index(op.f('ix_strategy_templates_usage_count'), 'strategy_templates', ['usage_count'], unique=False)
    op.create_index(op.f('ix_strategy_templates_user_id'), 'strategy_templates', ['user_id'], unique=False)
    op.create_index('ix_template_category_system', 'strategy_templates', ['category', 'is_system_template'], unique=False)
    op.create_index('ix_template_deleted_created', 'strategy_templates', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_template_usage_count_desc', 'strategy_templates', ['usage_count'], unique=False)
    op.create_index('ix_template_user_category', 'strategy_templates', ['user_id', 'category'], unique=False)
    op.create_table('strategy_instances',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Strategy instance name'),
    sa.Column('template_id', sa.String(length=36), nullable=True, comment='Reference to template (NULL for custom strategies)'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Owner user ID'),
    sa.Column('logic_flow', sa.JSON(), nullable=False, comment='Modified logic flow from template or custom'),
    sa.Column('parameters', sa.JSON(), server_default='{}', nullable=False, comment='User-configured parameter values'),
    sa.Column('status', sa.String(length=50), server_default='DRAFT', nullable=False, comment='Strategy status (DRAFT, TESTING, ACTIVE, ARCHIVED)'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='Version number for snapshots'),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True, comment='Reference to parent version (for version history)'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Deletion timestamp'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='User ID who last updated this record'),
    sa.CheckConstraint('version >= 1', name='check_version_positive'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['strategy_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['strategy_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Strategy instance storage table',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_instance_deleted_created', 'strategy_instances', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_instance_parent_version', 'strategy_instances', ['parent_version_id'], unique=False)
    op.create_index('ix_instance_template_user', 'strategy_instances', ['template_id', 'user_id'], unique=False)
    op.create_index('ix_instance_user_status', 'strategy_instances', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_strategy_instances_is_deleted'), 'strategy_instances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_strategy_instances_name'), 'strategy_instances', ['name'], unique=False)
    op.create_index(op.f('ix_strategy_instances_parent_version_id'), 'strategy_instances', ['parent_version_id'], unique=False)
    op.create_index(op.f('ix_strategy_instances_status'), 'strategy_instances', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_instances_template_id'), 'strategy_instances', ['template_id'], unique=False)
    op.create_index(op.f('ix_strategy_instances_user_id'), 'strategy_instances', ['user_id'], unique=False)
    op.create_table('template_ratings',
    sa.Column('template_id', sa.String(length=36), nullable=False, comment='Reference to rated template'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='User ID who rated the template'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='Rating value (1-5)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Optional rating comment'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Primary key (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False, comment='Soft delete flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Deletion timestamp'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(length=255), nullable=True, comment='User ID who last updated this record'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['template_id'], ['strategy_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Template rating storage table',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_rating_template_created', 'template_ratings', ['template_id', 'created_at'], unique=False)
    op.create_index('ix_rating_unique_user_template', 'template_ratings', ['user_id', 'template_id'], unique=True)
    op.create_index(op.f('ix_template_ratings_is_deleted'), 'template_ratings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_template_ratings_template_id'), 'template_ratings', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_ratings_user_id'), 'template_ratings', ['user_id'], unique=False)
    op.alter_column('chart_configs', 'config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Chart configuration (JSON object)',
               existing_nullable=False)
    op.alter_column('chart_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('chart_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('datasets', 'columns',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='[]',
               existing_comment='List of column names (JSON array)',
               existing_nullable=False)
    op.alter_column('datasets', 'metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Additional metadata (JSON object)',
               existing_nullable=False)
    op.alter_column('datasets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('datasets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('import_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('import_tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'configuration',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Rule configuration (JSON object)',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Additional rule metadata (JSON object)',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'execution_config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Execution configuration snapshot (JSON object)',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'progress_percentage',
               existing_type=mysql.FLOAT(),
               server_default='0.0',
               existing_comment='Progress percentage (0-100)',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('user_preferences', 'completed_guides',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='[]',
               existing_comment='List of completed onboarding guide IDs (JSON array)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'settings',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default='{}',
               existing_comment='Additional user-specific settings (JSON object)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preferences', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('user_preferences', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('user_preferences', 'settings',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Additional user-specific settings (JSON object)',
               existing_nullable=False)
    op.alter_column('user_preferences', 'completed_guides',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'[]'"),
               existing_comment='List of completed onboarding guide IDs (JSON array)',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'progress_percentage',
               existing_type=mysql.FLOAT(),
               server_default=sa.text('0'),
               existing_comment='Progress percentage (0-100)',
               existing_nullable=False)
    op.alter_column('preprocessing_tasks', 'execution_config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Execution configuration snapshot (JSON object)',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Additional rule metadata (JSON object)',
               existing_nullable=False)
    op.alter_column('preprocessing_rules', 'configuration',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Rule configuration (JSON object)',
               existing_nullable=False)
    op.alter_column('import_tasks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('import_tasks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('datasets', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('datasets', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('datasets', 'metadata',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Additional metadata (JSON object)',
               existing_nullable=False)
    op.alter_column('datasets', 'columns',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'[]'"),
               existing_comment='List of column names (JSON array)',
               existing_nullable=False)
    op.alter_column('chart_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record last update timestamp',
               existing_nullable=False)
    op.alter_column('chart_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_comment='Record creation timestamp',
               existing_nullable=False)
    op.alter_column('chart_configs', 'config',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               server_default=sa.text("'{}'"),
               existing_comment='Chart configuration (JSON object)',
               existing_nullable=False)
    op.drop_index(op.f('ix_template_ratings_user_id'), table_name='template_ratings')
    op.drop_index(op.f('ix_template_ratings_template_id'), table_name='template_ratings')
    op.drop_index(op.f('ix_template_ratings_is_deleted'), table_name='template_ratings')
    op.drop_index('ix_rating_unique_user_template', table_name='template_ratings')
    op.drop_index('ix_rating_template_created', table_name='template_ratings')
    op.drop_table('template_ratings')
    op.drop_index(op.f('ix_strategy_instances_user_id'), table_name='strategy_instances')
    op.drop_index(op.f('ix_strategy_instances_template_id'), table_name='strategy_instances')
    op.drop_index(op.f('ix_strategy_instances_status'), table_name='strategy_instances')
    op.drop_index(op.f('ix_strategy_instances_parent_version_id'), table_name='strategy_instances')
    op.drop_index(op.f('ix_strategy_instances_name'), table_name='strategy_instances')
    op.drop_index(op.f('ix_strategy_instances_is_deleted'), table_name='strategy_instances')
    op.drop_index('ix_instance_user_status', table_name='strategy_instances')
    op.drop_index('ix_instance_template_user', table_name='strategy_instances')
    op.drop_index('ix_instance_parent_version', table_name='strategy_instances')
    op.drop_index('ix_instance_deleted_created', table_name='strategy_instances')
    op.drop_table('strategy_instances')
    op.drop_index('ix_template_user_category', table_name='strategy_templates')
    op.drop_index('ix_template_usage_count_desc', table_name='strategy_templates')
    op.drop_index('ix_template_deleted_created', table_name='strategy_templates')
    op.drop_index('ix_template_category_system', table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_user_id'), table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_usage_count'), table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_name'), table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_is_system_template'), table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_is_deleted'), table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_category'), table_name='strategy_templates')
    op.drop_table('strategy_templates')
    # ### end Alembic commands ###
