"""Error Codes for Qlib-UI"""

class ErrorCode:
    # General errors
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # Data management errors
    DATA_IMPORT_ERROR = "DATA_IMPORT_ERROR"
    DATA_VALIDATION_FAILED = "DATA_VALIDATION_FAILED"
    DATA_PREPROCESSING_ERROR = "DATA_PREPROCESSING_ERROR"

    # Strategy errors
    STRATEGY_NOT_FOUND = "STRATEGY_NOT_FOUND"
    STRATEGY_VALIDATION_FAILED = "STRATEGY_VALIDATION_FAILED"
    STRATEGY_EXECUTION_ERROR = "STRATEGY_EXECUTION_ERROR"

    # Backtest errors
    BACKTEST_ERROR = "BACKTEST_ERROR"
    BACKTEST_TIMEOUT = "BACKTEST_TIMEOUT"
    BACKTEST_FAILED = "BACKTEST_FAILED"

    # Code execution errors
    CODE_EXECUTION_ERROR = "CODE_EXECUTION_ERROR"
    CODE_SECURITY_VIOLATION = "CODE_SECURITY_VIOLATION"
